root/events/urls.py
from django.urls import path, include

from events.views import (
    EventListView,
    EventDetailView,
    EventRegisterView,
    EventGuestContactCreateView,
)

app_name = "events"

urlpatterns = [
    path(
        "",
        include(
            [
                path("", EventListView.as_view(), name="events"),
                path("<int:pk>/", EventDetailView.as_view(), name="event"),
                path(
                    "<int:pk>/registration/register/",
                    EventRegisterView.as_view(),
                    name="register",
                ),
                # path(
                #     "<int:pk>/registration/cancel/",
                #     EventCancelView.as_view(),
                #     name="cancel",
                # ),
                path(
                    "<int:pk>/registration/",
                    EventGuestContactCreateView.as_view(),
                    name="registration",
                ),
            ]
        ),
    ),
]

root/loefsys/api/admin/urls.py
from django.urls import path, include

app_name = "loefsys"

urlpatterns = []

root/loefsys/api/urls.py
from django.conf import settings
from django.urls import path, include

from rest_framework.schemas import get_schema_view

app_name = "loefsys"

urlpatterns = [
    path("admin/", include("loefsys.api.admin.urls", namespace="admin")),
    path("", include("events.api.urls")),
    # path(
    #     "schema",
    #     get_schema_view(
    #         title="LoefAPI",
    #         version=1,
    #         url="/api/",
    #         urlconf="thaliawebsite.api.urls",
    #         generator_class=OAuthSchemaGenerator,
    #         public=True,
    #     ),
    #     name="schema",
    # ),
]

root/loefsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("loefsys.api.urls")),
    path("", views.index, name="index"),
    path("register/", views.index, name="index"),
    path("change-password/", auth_views.PasswordChangeView.as_view),
    path("login/", auth_views.LoginView.as_view),
    path("logout/", auth_views.LogoutView.as_view),
    # Apps
    path("members/", include("members.urls")),
    path("events/", include("events.urls")),
]

root/members/urls.py
from django.urls import path, include

from members.views import ProfileDetailView, ProfileListView

app_name = "members"

urlpatterns = [
    path("", ProfileListView.as_view(), name="members"),
    path(
        "",
        include(
            [
                path("profile/", ProfileDetailView.as_view(), name="profile"),
                path("profile/<int:pk>", ProfileDetailView.as_view(), name="profile"),
            ]
        ),
    ),
]

root/users/urls.py
from django.urls import path, include

from users.views import ProfileDetailView

app_name = "users"

urlpatterns = [
    path(
        "members/",
        include(
            [
                path("profile/", ProfileDetailView.as_view(), name="profile"),
                path("profile/<int:pk>", ProfileDetailView.as_view(), name="profile"),
            ]
        ),
    ),
]

root/loefsys/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

root/loefsys/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Loefbijter</title>
</head>
<body class="{% block body_class %}{% endblock %}">

<!--
{#<nav>#}
{#    {% if not user.is_authenticated %}#}
{#        <a href="{% url 'login' %}" class="btn btn-primary" title="Login"><i aria-hidden="true" class="fas fa-user"></i></a>#}
{#                {% else %}#}
{#                    <button type="button"#}
{#                            class="btn btn-primary dropdown-toggle dropdown-toggle-split"#}
{#                            data-bs-toggle="dropdown" aria-haspopup="true" id="user-menu-dropdown-button"#}
{#                            title="User options">#}
{#                        <i aria-hidden="true" class="fas fa-user pe-2"></i>#}
{#                    </button>#}
{#                    <ul class="dropdown-menu" aria-labelledby="user-menu-dropdown-button">#}
{#                            <li>#}
{#                                <a class="dropdown-item"#}
{#                                   href="{% url 'members:profile' %}">#}
{#                                    {% trans "show profile"|capfirst %}#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a class="dropdown-item"#}
{#                                   href="{% url 'members:edit-profile' %}">#}
{#                                    {% trans "edit profile"|capfirst %}#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a class="dropdown-item"#}
{#                                   href="{% url 'password_change' %}">#}
{#                                    {% trans "change password"|capfirst %}#}
{#                                </a>#}
{#                            </li>#}
{#                            <li><hr class="dropdown-divider"></li>#}
{#                            <li>#}
{#                                <a class="dropdown-item"#}
{#                                   href="{% url 'registrations:renew' %}">#}
{#                                    {% trans "manage membership"|capfirst %}#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a class="dropdown-item"#}
{#                                   href="{% url 'payments:payment-list' %}">#}
{#                                    {% trans "view payments"|capfirst %}#}
{#                                </a>#}
{#                            </li>#}
{#                            <li><hr class="dropdown-divider"></li>#}
{#                            <li>#}
{#                                <a class="dropdown-item"#}
{#                                   href="{% url 'admin:index' %}">#}
{#                                    {% trans "Site administration" %}#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a class="dropdown-item"#}
{#                                   href="{% url 'logout' %}">#}
{#                                    {% trans "Logout" %}#}
{#                                </a>#}
{#                            </li>#}
{#                    </ul>#}
{#                {% endif %}#}
{#</nav>>#}
-->

{% block pre-body %}{% endblock pre-body %}

<div id="page-content" class="clearfix">
    {% block body %}{% endblock body %}
</div>

{% block post-body %}{% endblock post-body %}

</body>
</html>

root/loefsys/templates/index.html
{% extends 'base.html' %}

{% block body_class %}home{% endblock %}

{% block body %}
<ul>
    <li><a href="{% url 'members:members' %}">Members</a></li>
    <li><a href="{% url 'events:events' %}">Events</a></li>
</ul>


{% endblock %}